"""empty message

Revision ID: 769354bcb780
Revises: 43f373f2a776
Create Date: 2020-09-23 20:54:20.926821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769354bcb780'
down_revision = '43f373f2a776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('title', sa.String(), nullable=True))
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pic')
    op.drop_column('users', 'about')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'date')
    # ### end Alembic commands ###
