"""empty message

Revision ID: d7d2b09154e5
Revises: 769354bcb780
Create Date: 2020-09-26 11:51:05.798474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d2b09154e5'
down_revision = '769354bcb780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('nick', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'nick')
    # ### end Alembic commands ###
